VM_BOX = "debian/buster64"
VM_IP = "172.29.1.10"
VM_MEMORY = 2048
VM_CPUS = 2

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: VM_IP

  config.vm.provider "virtualbox" do |v|
    v.memory = VM_MEMORY
    v.cpus = VM_CPUS
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3",
      external_address: VM_IP,
    }
  end
end
