#cloud-config

timezone: UTC

write_files:
  - path: /etc/ssh/sshd_config
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      Subsystem sftp internal-sftp

system_info:
  default_user:
    name: hetzner
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD: ALL"
