- hosts: all
  become: true

  vars:
    k3s_version: v1.20.0+k3s2
    k3s_installer_sum: sha1:d302e35feaf9580cbc687c97119e377f81882823

    authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGZ3csbA3hwqx+66aji0paL9wOYy3zB24YzAqYlJlMh2"

  tasks:

    # K3s

    - name: k3s install script is present
      get_url:
        url: https://github.com/k3s-io/k3s/raw/{{ k3s_version }}/install.sh
        checksum: "{{ k3s_installer_sum }}"
        dest: /root/k3s-install.sh
        mode: 0744

    - name: k3s is installed
      command: /root/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server --node-ip {{ k3s_address }}"

    - name: k3s remote access config is generated
      shell: |
        sed                                \
          's/127.0.0.1/{{ k3s_address }}/' \
          /etc/rancher/k3s/k3s.yaml        \
        > k3s-remote.yaml
      args:
        warn: false

    - name: k3s remote access config is downloaded
      fetch:
        src: k3s-remote.yaml
        dest: _k3s.yaml
        flat: true


    # Registry

    - name: registry is installed
      apt:
        name: docker-registry
        state: present


    # Docker

    - name: apt-key requirements are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
        state: present

    - name: apt key for docker repository is registered
      apt_key:
        id: 9dc858229fc7dd38854ae2d88d81803c0ebfcd88
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: docker repository is registered
      apt_repository:
        repo: >
          deb [arch=amd64]
          https://download.docker.com/linux/debian
          {{ ansible_lsb.codename }} stable
        state: present

    - name: docker is installed
      apt:
        name: docker-ce
        state: present


    # Git

    - name: git is installed
      apt:
        name: git
        state: present

    - name: git group is added
      group:
        name: git
        gid: 2000

    - name: git user is added
      user:
        name: git
        password: '*'
        shell: /usr/bin/bash
        group: git
        groups: docker
        uid: 2000

    - name: ssh directory exists
      file:
        path: /home/git/.ssh
        state: directory
        owner: git
        group: git

    - name: authorized keys are up
      copy:
        content: |
          {{ authorized_keys | join('\n') }}
        dest: /home/git/.ssh/authorized_keys
        mode: 0600
        owner: git
        group: git


    # myapp

    - name: myapp repository exists
      command: sudo -u git git init --bare /home/git/myapp
      args:
        creates: /home/git/myapp/HEAD

    - name: myapp hook is up
      copy:
        src: pre-receive.sh
        dest: /home/git/myapp/hooks/pre-receive
        owner: git
        group: git
        mode: 0755
