- hosts: localhost
  become: no
  connection: local
  gather_facts: no

  tasks:
    - name:
      template:
        src: foo.conf.j2
        dest: foo.conf
      vars:
        wireguard_private_key: ...
        wireguard_network: 10.20.30.0/24
        wireguard_port: 999
        wireguard_peers:
          - name: athena
            host_id: 10
            public_key: "MZdLZ4zGoadCVgS14kzeCSL37CQ75BJp1qUaPW2qklc="
          - name: hermes
            host_id: 11
            public_key: "PkZia0IqOKJt+9wvaUKCWKuaH59JeMts8jP9UAP4Tz4="
          - name: iris
            host_id: 12
            public_key: "Q4loju7j5BBHIvQZUf8lzGcYY8tD7tw7+ACqB9DPfms="
          - name: perseus
            host_id: 13
            public_key: "jK5BPpmaCRF8l4CcFUfxu9TmDN1IVQUK+cO0Nlb8ITM="
