apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp
  labels: &labels
    app: myapp

spec:
  replicas: 1

  selector:
    matchLabels: *labels

  template:
    metadata:
      labels: *labels

    spec:
      containers:
        - name: main
          image: busybox
          command: ["sleep", "infinity"]
          volumeMounts: &mounts
            - name: storage
              mountPath: /data
          securityContext:
            runAsUser: 1234
            runAsGroup: 5678

      initContainers:
        # fsGroup does not work for NFS volumes. So we use an init container to
        # fixup the owner of the volume.
        - name: chown
          image: busybox
          command: ["chown", "-R", "1234:5678", "/data"]
          volumeMounts: *mounts

      volumes:
        - name: storage
          nfs:
            server: "{{ ansible_default_ipv4.address }}"
            path: /myapp
