---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: seaweedfs-storage

  # Specifying volumeName keeps PVC exiting from pending state.
  # volumeName: test-volume
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: test-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-volume-pvc
