- name: k3s installer script is downloaded
  get_url:
    url: https://get.k3s.io
    dest: /root/install-k3s.bash

- name: k3s is installed
  command: bash /root/install-k3s.bash
  args:
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: "server --tls-san {{ k3s_address }} --no-deploy traefik"

- name: k3s is activated
  service:
    name: k3s
    state: started
    enabled: true
