CXXFLAGS = \
  -std=c++17 \
  -pedantic \
  -Wall \
  -Wextra \
  -Wconversion \
  $(INCLUDES)

INCLUDES = \
  -isystem ../submodules/github.com/docopt/docopt.cpp

.PHONY: all clean

all: main
	@:

clean:
	rm -f main
