- hosts: default
  become: true

  tasks:
    - name: apt cache is up
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: unattended-upgrades is installed
      apt:
        name: unattended-upgrades
        state: present

    - name: unattended-upgrades is activated
      copy:
        content: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        dest: /etc/apt/apt.conf.d/20auto-upgrades

    - name: Unattended-upgrades can run on AC power
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::OnlyOnACPower "false";
        state: present

    # https://www.databasesandlife.com/vagrant-debian10-grub/
    - name: grub-pc is held
      dpkg_selections:
        name: grub-pc
        selection: hold
