---
apiVersion: v1
kind: Namespace

metadata:
  name: myapp


---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: myapp
  name: main
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: nginx
          containerPort: 80


---
apiVersion: v1
kind: Service

metadata:
  namespace: myapp
  name: main

spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: nginx
  selector:
    app: nginx
