kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test
      image: busybox
      volumeMounts:
        - mountPath: "/data"
          name: test-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-volume-pvc
