---
apiVersion: v1
kind: Namespace

metadata:
  name: myapp


---
apiVersion: v1
kind: Pod

metadata:
  namespace: myapp
  name: shell

spec:
  containers:
    - name: shell
      image: ubuntu:20.04
      volumeMounts:
        - mountPath: /data
          name: storage
      command: ["/usr/bin/sleep", "infinity"]
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storage


---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: myapp
  name: storage

spec:
  resources:
    requests:
      storage: 128Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
