---
apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: nfs

provisioner: nfs.csi.k8s.io
parameters:
  server: nfs.internal
  share: /
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4
