CXXFLAGS = \
  -std=c++2a \
  -Wpedantic \
  -Wall \
  -Wextra \
  -Wconversion \
  -Wsign-conversion \
  -O2 \
  -isystem../submodules/github.com/danielaparker/jsoncons/include

.PHONY: all clean

all: main
	@:

clean:
	rm -f main
