---
apiVersion: v1
kind: Namespace

metadata:
  name: myapp


---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: myapp
  name: web
  labels: &labels
    app: web

spec:
  replicas: 2
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: nginx
          image: nginx:1
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service

metadata:
  namespace: myapp
  name: web

spec:
  ports:
    - port: 80
  selector:
    app: web


---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  namespace: myapp
  name: web
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  rules:
    - host: myapp.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
