- hosts: all
  become: true

  vars:
    seaweed_version: "2.04"

  tasks:
    - name: seaweed group is present
      group:
        gid: 4000
        name: seaweed
        state: present

    - name: seaweed user is present
      user:
        uid: 4000
        name: seaweed
        group: seaweed
        system: true
        create_home: false
        password: '*'
        state: present

    - name: seaweed data directory is present
      file:
        path: /var/lib/seaweed
        owner: seaweed
        group: seaweed
        mode: 0700
        state: directory

    - name: seaweed executable is present
      unarchive:
        remote_src: true
        src: "https://github.com/chrislusf/seaweedfs/releases/download/{{ seaweed_version }}/linux_amd64.tar.gz"
        dest: /usr/sbin
        creates: /usr/sbin/weed

    - name: seaweed service unit is present
      copy:
        src: seaweed.service
        dest: /etc/systemd/system

    - name: seaweed service is activated
      systemd:
        service: seaweed
        enabled: true
        state: started
