---
apiVersion: v1
kind: Namespace

metadata:
  name: whoami

---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: whoami
  name: main
  labels: &labels
    app: whoami

spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service

metadata:
  namespace: whoami
  name: web

spec:
  ports:
    - port: 80
  selector:
    app: whoami

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  namespace: whoami
  name: websecure

spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.illil.io`)
      services:
        - name: web
          port: 80
  tls:
    certResolver: letsencrypt-staging


---
# `entryPoints: [web, websecure]` does not serve HTTP and HTTPS on the same
# ingree route... so we add an HTTP route here.
# https://community.traefik.io/t/kubernetes-intress-http-works-https-not/8628

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  namespace: whoami
  name: web

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`whoami.illil.io`)
      services:
        - name: web
          port: 80
