---
apiVersion: v1
kind: Namespace

metadata:
  name: myapp


---
apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: myapp
  name: main
  labels:
    app: main

spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: scratch
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service

metadata:
  namespace: myapp
  name: main

spec:
  ports:
  - port: 80
  selector:
    app: main


---
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  namespace: myapp
  name: main
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: main
          servicePort: 80
