VM_BOX = "debian/buster64"
VM_IP = "172.29.1.10"

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.network :private_network, ip: VM_IP
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
end
