- hosts: localhost
  connection: local
  become: no
  gather_facts: no

  tasks:

    - name: Groups
      debug:
        msg: "{{ groups }}"

    - name: Hosts
      debug:
        msg: "{{ hostvars[item].ansible_host }}"
      with_items: "{{ groups['all'] }}"
