CXXFLAGS = \
  $(WARNFLAGS) \
  $(OPTFLAGS)

WARNFLAGS = \
  -std=c++20 \
  -Wpedantic \
  -Wall \
  -Wextra \
  -Wconversion \
  -Wsign-conversion

OPTFLAGS = \
  -O2


.PHONY: all clean

run: main
	@:

clean:
	rm -f main
