VM_CPUS = 1
VM_MEMORY = 512
VM_BOX = "bento/freebsd-12.1"

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.cpus = VM_CPUS
    v.memory = VM_MEMORY
  end
  config.vm.box = VM_BOX
end
