VM_CPUS = 2
VM_MEMORY = 1024
VM_BOX = "bento/freebsd-12.1"

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX

  config.vm.provider :virtualbox do |v|
    v.cpus = VM_CPUS
    v.memory = VM_MEMORY
  end

  config.vm.provision :shell, path: "provision.sh"
end
