- hosts: all
  become: true

  vars:
    k3s_version: v1.20.0+k3s2
    k3s_installer_sum: sha1:d302e35feaf9580cbc687c97119e377f81882823

  tasks:

    # K3s

    - name: k3s install script is present
      get_url:
        url: https://github.com/k3s-io/k3s/raw/{{ k3s_version }}/install.sh
        checksum: "{{ k3s_installer_sum }}"
        dest: /root/k3s-install.sh
        mode: 0744

    - name: k3s is installed
      command: /root/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server --node-ip {{ k3s_address }}"

    - name: k3s remote access config is generated
      shell: |
        sed                                \
          's/127.0.0.1/{{ k3s_address }}/' \
          /etc/rancher/k3s/k3s.yaml        \
        > k3s-remote.yaml
      args:
        warn: false

    - name: k3s remote access config is downloaded
      fetch:
        src: k3s-remote.yaml
        dest: _k3s.yaml
        flat: true

    # registry

    - name: registry is innstalled
      apt:
        name: docker-registry
        state: present
