- hosts: default
  become: true

  vars:
    k3s_version: v1.20.2+k3s1
    k3s_installer_sum: sha256:c63032985492e6fb3e7642b244a22ec7ad2f5a4f023a729de77b941dd19c6a59

  tasks:

    - name: k3s install script is present
      get_url:
        url: https://github.com/k3s-io/k3s/raw/{{ k3s_version }}/install.sh
        checksum: "{{ k3s_installer_sum }}"
        dest: /root/k3s-install.sh
        mode: "744"

    - name: k3s config directory is present
      file:
        path: /etc/rancher/k3s
        state: directory

    - name: k3s-server manifests directory is present
      file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory

    - name: k3s config is up
      copy:
        content: |
          write-kubeconfig-mode: "644"
          disable: traefik
        dest: /etc/rancher/k3s/config.yaml

    - name: traefik-v2 chart is up
      copy:
        src: traefik-v2.yaml
        dest: /var/lib/rancher/k3s/server/manifests/

    - name: traefik-v2 chart config is up
      copy:
        src: traefik-v2-config.yaml
        dest: /var/lib/rancher/k3s/server/manifests/

    - name: k3s is installed
      command: /root/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"

    - name: curl is installed
      apt:
        name: curl
        state: present


- hosts: default

  tasks:
    - name: sample manifest is up
      copy:
        src: sample.yaml
        dest: .
