apiVersion: helm.cattle.io/v1
kind: HelmChartConfig

metadata:
  name: traefik
  namespace: kube-system

spec:
  valuesContent: |
    additionalArguments:
      - --certificatesresolvers.le-test.acme.email=snsinfu+LE@gmail.com
      - --certificatesresolvers.le-test.acme.storage=/data/acme.json
      - --certificatesresolvers.le-test.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    persistence:
      enabled: true
      path: /data

    # Below is K3s' default chart configuration.
    rbac:
      enabled: true
    ports:
      websecure:
        tls:
          enabled: true
    podAnnotations:
      prometheus.io/port: "8082"
      prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      name: "rancher/library-traefik"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
